services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: testmarkdb-app
    container_name: web-app
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=root.settings
    command: ["uwsgi", "--ini", "./uwsgi.ini"]    
    expose:
      - "8000"
    env_file:
      - ./.env
    volumes:
      - ./server/certs/:/app/server/certs:ro

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: testmarkdb-nginx
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "8800:80"
    depends_on:
      - web

  celery:
    image: testmarkdb-app
    container_name: celery-worker
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=root.settings
    command: ["celery", "-A", "root", "worker", "--loglevel=INFO"]    
    env_file:
      - ./.env
    volumes:
      - ./server/certs/:/app/server/certs:ro
    depends_on:
      - web
